### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by bspdeveloper** [3ddelano/gogoanime-batch-downloader#2]
It says MP4 Not Found

**Comment by 3ddelano** [comment]
This package needs to be updated since Gogo anime added captcha check if you try to many requests from the same IP

**Comment by 3ddelano** [comment]
As a workaround try to download only HDP quality videos.

**Comment by KillrOfLife** [comment]
doesn't work on HDP either

**Comment by 3ddelano** [comment]
Closed since captcha check needs a paid API service.
