### ISSUE TITLE
Doesn't Open

### ISSUE THREAD

**Issue by singhantariksh** [3ddelano/gogoanime-batch-downloader#3]
I had Python 3.10 and when I was opening cmd it was showing "python not found", I realized Python wasn't  updated so I downloaded the latest version (3.11) and it is still showing the same thing "Python not found" when opening command file...

**Comment by 3ddelano** [comment]
In the `run.cmd` file, try changing the word `python` to `python3` and see if it works. It seems to be that python isn't added to the `PATH` environment variable. See more information here [Add python to path](https://realpython.com/add-python-to-path)

**Comment by singhantariksh** [comment]
I've added Python path and python\scripts path to PATH and it didn't showed the error I mentioned previously, now it showed module not found. I then surfed around the web and finally installed pip and the dependencies your code requires, now it's working, only thing left is to test it properly ! your thingy made me learn some vital information thanks !

edit : Hey man ! I'm downloading dragon ball Z dub and I did follow the instructions and everything, put the first episode link, start and end, quality I chose 480 (typed 3) and name and stuff. its showing mp4 not found now ;-;

**Comment by 3ddelano** [comment]
It seems this code isn't working anymore because gogoanime added Captcha verification in an attempt to reduce bot scraping. If you want to bypass this Captcha you would need a paid API.

**Comment by singhantariksh** [comment]
Ah bad luck ! You can close this now man. thanks for the help anyways :)

**Comment by 3ddelano** [comment]
No problem! Btw I found this app very handy for anime [Aniyomi](https://github.com/jmir1/aniyomi)
